wdi:  "Web Development Immersive"
uxdi: "User Experience Design Immersive"
dsi:  "Data Science Immersive"
pmi:  "Product Management Immersive"
fewd: "Front-End Web Design, Part-Time"
bewd: "Back-End Web Design, Part-Time"
